version: '3.8'
services: 
  app: 
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mysql-server
  mysql-server:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: appsecdb
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password