version: '3.9'
services: 

  # Pulls reverse-proxy server docker image
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    container_name: reverse-proxy
    depends_on:
      - next-app
      - mysql-server
    ports:
      - 80:8080
      - 443:8443

  # Builds application server docker image
  next-app: 
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: next-app
    environment:
      DB_HOST: mysql-server
      DB_USER: app
      DB_PASSWORD: V6m#4&hE896O5I7he=ropR4mls2=t7+swibodi=Re!8acrU+8afr8StUFeR_0?ad
      DB_NAME: appsecdb
    depends_on:
      - mysql-server
    restart: on-failure

  # Pulls mysql server docker image
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    volumes:
      - ./database/:/var/lib/mysql/
    ports: 
      - 3306:3306