version: '3.8'
services: 

  # Pulls reverse-proxy server docker image
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    container_name: reverse-proxy
    depends_on:
      - next-app
      - mysql-server
    ports:
      - 80:8080
      - 443:8443

  # Builds application server docker image
  next-app: 
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: next-app
    environment:
      - DB_HOST=mysql-server
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=appsecdb
    depends_on:
      - mysql-server
    restart: on-failure

  # Pulls mysql server docker image
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    volumes:
      - ./database/:/var/lib/mysql/
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: appsecdb
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password